name: Build WF
on: 
  #push:
  #  branches:
  #    - main

  pull_request:
         branches:
          - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Maven build
        run: mvn clean install 
  
  Testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Maven test
        run: mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle