name: Build WF
on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '10 14 * * 1-5'

env: 
  ECR_REPOSITORY: 'vprofile-appimage'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Maven build
        run: mvn clean install 

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify build failure
        if: failure()
        run: echo "Build failed! Please check the logs for details."
  
  Testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Maven test
        if: github.ref == 'refs/heads/main' 
        run: mvn test

      - name: checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "skipping unit tests for non-main branch"
  
  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Run Trivy security scan
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: 'os,library'
          output: 'trivy-report.json'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: trivy-report
          path: trivy-report.json

  BUILD_AND_PUBLISH:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    environment: production
    needs: [build, Testing, security-scan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: code checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1.0.0

      - name: Build and Push Docker Image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/vprofile-app:$IMAGE_TAG .
          docker push $ECR_REGISTRY/vprofile-app:$IMAGE_TAG
         